# set UTF-8
export LC_ALL=en_US.UTF-8

# set us:alt-intl layout
setxkbmap us -variant altgr-intl -option nodeadkeys

# xautolock will lock your display after a period of inactivity
xautolock -time 10 -locker slock &

# init dwmblocks
xterm &

# init cwm
exec cwm
